### ISSUE TITLE
Expose other Redis SET options

### ISSUE THREAD

**Issue by sylv** [sylodev/kas#6]
The SET command has various options, most of which aren't available or would be but types forbid it. Specifically I need the `KEEPTTL` option but it's unavailable. This can probably be fixed by adding [these options](https://redis.io/commands/set/#options) to the `SetOption` enum. For future-proofing, it might be nice to make the `mode` parameter a `SetOption | string` type.

It would also be nice if you could provide an array of options, so you can mix and match when necessary.

**Comment by cykreet** [comment]
I hesitate having the `mode` option also support strings, since that would make the user experience a little messy - since it's just appended to the command, it could literally be used for anything beyond options. Adding the `KEEPTTL` option and support for an array of options is easy enough for now though.

Here's to a Great [Day of the Week],
Uncle

**Comment by sylv** [comment]
Thank you uncle 🙏

**Comment by cykreet** [comment]
320b3b2 :)
